# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diretiva', '0004_auto_20170928_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretiva',
            name='date_entry',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diretiva',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diretiva',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
