# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 11:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiretivaEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateTimeField(auto_now=True, verbose_name='data da ultima atualiza\xe7\xe3o.')),
                ('status', models.BooleanField(default=False, verbose_name='status da diretiva')),
                ('product', models.CharField(default='Product', max_length=120, verbose_name='o produto que est\xe1 sendo referenciado')),
                ('tickets', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='ticket(s) atrelado(s) a diretiva.')),
                ('description', models.TextField(verbose_name='descri\xe7\xe3o da diretiva.')),
            ],
        ),
    ]
