# Generated by Django 2.0 on 2017-12-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diretiva', '0005_auto_20170928_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretiva',
            name='main_ticket',
            field=models.TextField(max_length=6),
        ),
    ]
