# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diretiva', '0002_auto_20170926_2057'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='diretiva',
            order_with_respect_to='date_entry',
        ),
    ]
